# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/share/cmake-3.12.0/bin/cmake

# The command to remove a file.
RM = /usr/share/cmake-3.12.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/constantine/文档/Code/Ambr3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/constantine/文档/Code/Ambr3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/share/cmake-3.12.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/share/cmake-3.12.0/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/constantine/文档/Code/Ambr3/CMakeFiles /home/constantine/文档/Code/Ambr3/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/constantine/文档/Code/Ambr3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Ambr

# Build rule for target.
Ambr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Ambr
.PHONY : Ambr

# fast build rule for target.
Ambr/fast:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/build
.PHONY : Ambr/fast

arch/linux/platform.o: arch/linux/platform.cc.o

.PHONY : arch/linux/platform.o

# target to build an object file
arch/linux/platform.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/arch/linux/platform.cc.o
.PHONY : arch/linux/platform.cc.o

arch/linux/platform.i: arch/linux/platform.cc.i

.PHONY : arch/linux/platform.i

# target to preprocess a source file
arch/linux/platform.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/arch/linux/platform.cc.i
.PHONY : arch/linux/platform.cc.i

arch/linux/platform.s: arch/linux/platform.cc.s

.PHONY : arch/linux/platform.s

# target to generate assembly for a file
arch/linux/platform.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/arch/linux/platform.cc.s
.PHONY : arch/linux/platform.cc.s

libs/ed25519-donna/ed25519.o: libs/ed25519-donna/ed25519.c.o

.PHONY : libs/ed25519-donna/ed25519.o

# target to build an object file
libs/ed25519-donna/ed25519.c.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/libs/ed25519-donna/ed25519.c.o
.PHONY : libs/ed25519-donna/ed25519.c.o

libs/ed25519-donna/ed25519.i: libs/ed25519-donna/ed25519.c.i

.PHONY : libs/ed25519-donna/ed25519.i

# target to preprocess a source file
libs/ed25519-donna/ed25519.c.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/libs/ed25519-donna/ed25519.c.i
.PHONY : libs/ed25519-donna/ed25519.c.i

libs/ed25519-donna/ed25519.s: libs/ed25519-donna/ed25519.c.s

.PHONY : libs/ed25519-donna/ed25519.s

# target to generate assembly for a file
libs/ed25519-donna/ed25519.c.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/libs/ed25519-donna/ed25519.c.s
.PHONY : libs/ed25519-donna/ed25519.c.s

src/core/key.o: src/core/key.cc.o

.PHONY : src/core/key.o

# target to build an object file
src/core/key.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/core/key.cc.o
.PHONY : src/core/key.cc.o

src/core/key.i: src/core/key.cc.i

.PHONY : src/core/key.i

# target to preprocess a source file
src/core/key.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/core/key.cc.i
.PHONY : src/core/key.cc.i

src/core/key.s: src/core/key.cc.s

.PHONY : src/core/key.s

# target to generate assembly for a file
src/core/key.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/core/key.cc.s
.PHONY : src/core/key.cc.s

src/core/node.o: src/core/node.cc.o

.PHONY : src/core/node.o

# target to build an object file
src/core/node.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/core/node.cc.o
.PHONY : src/core/node.cc.o

src/core/node.i: src/core/node.cc.i

.PHONY : src/core/node.i

# target to preprocess a source file
src/core/node.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/core/node.cc.i
.PHONY : src/core/node.cc.i

src/core/node.s: src/core/node.cc.s

.PHONY : src/core/node.s

# target to generate assembly for a file
src/core/node.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/core/node.cc.s
.PHONY : src/core/node.cc.s

src/core/unit.o: src/core/unit.cc.o

.PHONY : src/core/unit.o

# target to build an object file
src/core/unit.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/core/unit.cc.o
.PHONY : src/core/unit.cc.o

src/core/unit.i: src/core/unit.cc.i

.PHONY : src/core/unit.i

# target to preprocess a source file
src/core/unit.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/core/unit.cc.i
.PHONY : src/core/unit.cc.i

src/core/unit.s: src/core/unit.cc.s

.PHONY : src/core/unit.s

# target to generate assembly for a file
src/core/unit.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/core/unit.cc.s
.PHONY : src/core/unit.cc.s

src/crypto/blake2/blake2b.o: src/crypto/blake2/blake2b.cc.o

.PHONY : src/crypto/blake2/blake2b.o

# target to build an object file
src/crypto/blake2/blake2b.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/crypto/blake2/blake2b.cc.o
.PHONY : src/crypto/blake2/blake2b.cc.o

src/crypto/blake2/blake2b.i: src/crypto/blake2/blake2b.cc.i

.PHONY : src/crypto/blake2/blake2b.i

# target to preprocess a source file
src/crypto/blake2/blake2b.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/crypto/blake2/blake2b.cc.i
.PHONY : src/crypto/blake2/blake2b.cc.i

src/crypto/blake2/blake2b.s: src/crypto/blake2/blake2b.cc.s

.PHONY : src/crypto/blake2/blake2b.s

# target to generate assembly for a file
src/crypto/blake2/blake2b.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/crypto/blake2/blake2b.cc.s
.PHONY : src/crypto/blake2/blake2b.cc.s

src/main.o: src/main.cc.o

.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/main.cc.s
.PHONY : src/main.cc.s

src/p2p/addrdb.o: src/p2p/addrdb.cc.o

.PHONY : src/p2p/addrdb.o

# target to build an object file
src/p2p/addrdb.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/addrdb.cc.o
.PHONY : src/p2p/addrdb.cc.o

src/p2p/addrdb.i: src/p2p/addrdb.cc.i

.PHONY : src/p2p/addrdb.i

# target to preprocess a source file
src/p2p/addrdb.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/addrdb.cc.i
.PHONY : src/p2p/addrdb.cc.i

src/p2p/addrdb.s: src/p2p/addrdb.cc.s

.PHONY : src/p2p/addrdb.s

# target to generate assembly for a file
src/p2p/addrdb.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/addrdb.cc.s
.PHONY : src/p2p/addrdb.cc.s

src/p2p/addrman.o: src/p2p/addrman.cc.o

.PHONY : src/p2p/addrman.o

# target to build an object file
src/p2p/addrman.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/addrman.cc.o
.PHONY : src/p2p/addrman.cc.o

src/p2p/addrman.i: src/p2p/addrman.cc.i

.PHONY : src/p2p/addrman.i

# target to preprocess a source file
src/p2p/addrman.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/addrman.cc.i
.PHONY : src/p2p/addrman.cc.i

src/p2p/addrman.s: src/p2p/addrman.cc.s

.PHONY : src/p2p/addrman.s

# target to generate assembly for a file
src/p2p/addrman.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/addrman.cc.s
.PHONY : src/p2p/addrman.cc.s

src/p2p/arith_uint256.o: src/p2p/arith_uint256.cc.o

.PHONY : src/p2p/arith_uint256.o

# target to build an object file
src/p2p/arith_uint256.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/arith_uint256.cc.o
.PHONY : src/p2p/arith_uint256.cc.o

src/p2p/arith_uint256.i: src/p2p/arith_uint256.cc.i

.PHONY : src/p2p/arith_uint256.i

# target to preprocess a source file
src/p2p/arith_uint256.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/arith_uint256.cc.i
.PHONY : src/p2p/arith_uint256.cc.i

src/p2p/arith_uint256.s: src/p2p/arith_uint256.cc.s

.PHONY : src/p2p/arith_uint256.s

# target to generate assembly for a file
src/p2p/arith_uint256.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/arith_uint256.cc.s
.PHONY : src/p2p/arith_uint256.cc.s

src/p2p/chainparams.o: src/p2p/chainparams.cc.o

.PHONY : src/p2p/chainparams.o

# target to build an object file
src/p2p/chainparams.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/chainparams.cc.o
.PHONY : src/p2p/chainparams.cc.o

src/p2p/chainparams.i: src/p2p/chainparams.cc.i

.PHONY : src/p2p/chainparams.i

# target to preprocess a source file
src/p2p/chainparams.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/chainparams.cc.i
.PHONY : src/p2p/chainparams.cc.i

src/p2p/chainparams.s: src/p2p/chainparams.cc.s

.PHONY : src/p2p/chainparams.s

# target to generate assembly for a file
src/p2p/chainparams.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/chainparams.cc.s
.PHONY : src/p2p/chainparams.cc.s

src/p2p/chainparamsbase.o: src/p2p/chainparamsbase.cc.o

.PHONY : src/p2p/chainparamsbase.o

# target to build an object file
src/p2p/chainparamsbase.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/chainparamsbase.cc.o
.PHONY : src/p2p/chainparamsbase.cc.o

src/p2p/chainparamsbase.i: src/p2p/chainparamsbase.cc.i

.PHONY : src/p2p/chainparamsbase.i

# target to preprocess a source file
src/p2p/chainparamsbase.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/chainparamsbase.cc.i
.PHONY : src/p2p/chainparamsbase.cc.i

src/p2p/chainparamsbase.s: src/p2p/chainparamsbase.cc.s

.PHONY : src/p2p/chainparamsbase.s

# target to generate assembly for a file
src/p2p/chainparamsbase.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/chainparamsbase.cc.s
.PHONY : src/p2p/chainparamsbase.cc.s

src/p2p/compat/glibc_compat.o: src/p2p/compat/glibc_compat.cc.o

.PHONY : src/p2p/compat/glibc_compat.o

# target to build an object file
src/p2p/compat/glibc_compat.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/compat/glibc_compat.cc.o
.PHONY : src/p2p/compat/glibc_compat.cc.o

src/p2p/compat/glibc_compat.i: src/p2p/compat/glibc_compat.cc.i

.PHONY : src/p2p/compat/glibc_compat.i

# target to preprocess a source file
src/p2p/compat/glibc_compat.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/compat/glibc_compat.cc.i
.PHONY : src/p2p/compat/glibc_compat.cc.i

src/p2p/compat/glibc_compat.s: src/p2p/compat/glibc_compat.cc.s

.PHONY : src/p2p/compat/glibc_compat.s

# target to generate assembly for a file
src/p2p/compat/glibc_compat.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/compat/glibc_compat.cc.s
.PHONY : src/p2p/compat/glibc_compat.cc.s

src/p2p/compat/glibc_sanity.o: src/p2p/compat/glibc_sanity.cc.o

.PHONY : src/p2p/compat/glibc_sanity.o

# target to build an object file
src/p2p/compat/glibc_sanity.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/compat/glibc_sanity.cc.o
.PHONY : src/p2p/compat/glibc_sanity.cc.o

src/p2p/compat/glibc_sanity.i: src/p2p/compat/glibc_sanity.cc.i

.PHONY : src/p2p/compat/glibc_sanity.i

# target to preprocess a source file
src/p2p/compat/glibc_sanity.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/compat/glibc_sanity.cc.i
.PHONY : src/p2p/compat/glibc_sanity.cc.i

src/p2p/compat/glibc_sanity.s: src/p2p/compat/glibc_sanity.cc.s

.PHONY : src/p2p/compat/glibc_sanity.s

# target to generate assembly for a file
src/p2p/compat/glibc_sanity.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/compat/glibc_sanity.cc.s
.PHONY : src/p2p/compat/glibc_sanity.cc.s

src/p2p/compat/glibcxx_sanity.o: src/p2p/compat/glibcxx_sanity.cc.o

.PHONY : src/p2p/compat/glibcxx_sanity.o

# target to build an object file
src/p2p/compat/glibcxx_sanity.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/compat/glibcxx_sanity.cc.o
.PHONY : src/p2p/compat/glibcxx_sanity.cc.o

src/p2p/compat/glibcxx_sanity.i: src/p2p/compat/glibcxx_sanity.cc.i

.PHONY : src/p2p/compat/glibcxx_sanity.i

# target to preprocess a source file
src/p2p/compat/glibcxx_sanity.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/compat/glibcxx_sanity.cc.i
.PHONY : src/p2p/compat/glibcxx_sanity.cc.i

src/p2p/compat/glibcxx_sanity.s: src/p2p/compat/glibcxx_sanity.cc.s

.PHONY : src/p2p/compat/glibcxx_sanity.s

# target to generate assembly for a file
src/p2p/compat/glibcxx_sanity.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/compat/glibcxx_sanity.cc.s
.PHONY : src/p2p/compat/glibcxx_sanity.cc.s

src/p2p/compat/strnlen.o: src/p2p/compat/strnlen.cc.o

.PHONY : src/p2p/compat/strnlen.o

# target to build an object file
src/p2p/compat/strnlen.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/compat/strnlen.cc.o
.PHONY : src/p2p/compat/strnlen.cc.o

src/p2p/compat/strnlen.i: src/p2p/compat/strnlen.cc.i

.PHONY : src/p2p/compat/strnlen.i

# target to preprocess a source file
src/p2p/compat/strnlen.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/compat/strnlen.cc.i
.PHONY : src/p2p/compat/strnlen.cc.i

src/p2p/compat/strnlen.s: src/p2p/compat/strnlen.cc.s

.PHONY : src/p2p/compat/strnlen.s

# target to generate assembly for a file
src/p2p/compat/strnlen.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/compat/strnlen.cc.s
.PHONY : src/p2p/compat/strnlen.cc.s

src/p2p/crypto/aes.o: src/p2p/crypto/aes.cc.o

.PHONY : src/p2p/crypto/aes.o

# target to build an object file
src/p2p/crypto/aes.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/aes.cc.o
.PHONY : src/p2p/crypto/aes.cc.o

src/p2p/crypto/aes.i: src/p2p/crypto/aes.cc.i

.PHONY : src/p2p/crypto/aes.i

# target to preprocess a source file
src/p2p/crypto/aes.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/aes.cc.i
.PHONY : src/p2p/crypto/aes.cc.i

src/p2p/crypto/aes.s: src/p2p/crypto/aes.cc.s

.PHONY : src/p2p/crypto/aes.s

# target to generate assembly for a file
src/p2p/crypto/aes.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/aes.cc.s
.PHONY : src/p2p/crypto/aes.cc.s

src/p2p/crypto/chacha20.o: src/p2p/crypto/chacha20.cc.o

.PHONY : src/p2p/crypto/chacha20.o

# target to build an object file
src/p2p/crypto/chacha20.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/chacha20.cc.o
.PHONY : src/p2p/crypto/chacha20.cc.o

src/p2p/crypto/chacha20.i: src/p2p/crypto/chacha20.cc.i

.PHONY : src/p2p/crypto/chacha20.i

# target to preprocess a source file
src/p2p/crypto/chacha20.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/chacha20.cc.i
.PHONY : src/p2p/crypto/chacha20.cc.i

src/p2p/crypto/chacha20.s: src/p2p/crypto/chacha20.cc.s

.PHONY : src/p2p/crypto/chacha20.s

# target to generate assembly for a file
src/p2p/crypto/chacha20.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/chacha20.cc.s
.PHONY : src/p2p/crypto/chacha20.cc.s

src/p2p/crypto/hmac_sha256.o: src/p2p/crypto/hmac_sha256.cc.o

.PHONY : src/p2p/crypto/hmac_sha256.o

# target to build an object file
src/p2p/crypto/hmac_sha256.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/hmac_sha256.cc.o
.PHONY : src/p2p/crypto/hmac_sha256.cc.o

src/p2p/crypto/hmac_sha256.i: src/p2p/crypto/hmac_sha256.cc.i

.PHONY : src/p2p/crypto/hmac_sha256.i

# target to preprocess a source file
src/p2p/crypto/hmac_sha256.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/hmac_sha256.cc.i
.PHONY : src/p2p/crypto/hmac_sha256.cc.i

src/p2p/crypto/hmac_sha256.s: src/p2p/crypto/hmac_sha256.cc.s

.PHONY : src/p2p/crypto/hmac_sha256.s

# target to generate assembly for a file
src/p2p/crypto/hmac_sha256.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/hmac_sha256.cc.s
.PHONY : src/p2p/crypto/hmac_sha256.cc.s

src/p2p/crypto/hmac_sha512.o: src/p2p/crypto/hmac_sha512.cc.o

.PHONY : src/p2p/crypto/hmac_sha512.o

# target to build an object file
src/p2p/crypto/hmac_sha512.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/hmac_sha512.cc.o
.PHONY : src/p2p/crypto/hmac_sha512.cc.o

src/p2p/crypto/hmac_sha512.i: src/p2p/crypto/hmac_sha512.cc.i

.PHONY : src/p2p/crypto/hmac_sha512.i

# target to preprocess a source file
src/p2p/crypto/hmac_sha512.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/hmac_sha512.cc.i
.PHONY : src/p2p/crypto/hmac_sha512.cc.i

src/p2p/crypto/hmac_sha512.s: src/p2p/crypto/hmac_sha512.cc.s

.PHONY : src/p2p/crypto/hmac_sha512.s

# target to generate assembly for a file
src/p2p/crypto/hmac_sha512.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/hmac_sha512.cc.s
.PHONY : src/p2p/crypto/hmac_sha512.cc.s

src/p2p/crypto/ripemd160.o: src/p2p/crypto/ripemd160.cc.o

.PHONY : src/p2p/crypto/ripemd160.o

# target to build an object file
src/p2p/crypto/ripemd160.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/ripemd160.cc.o
.PHONY : src/p2p/crypto/ripemd160.cc.o

src/p2p/crypto/ripemd160.i: src/p2p/crypto/ripemd160.cc.i

.PHONY : src/p2p/crypto/ripemd160.i

# target to preprocess a source file
src/p2p/crypto/ripemd160.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/ripemd160.cc.i
.PHONY : src/p2p/crypto/ripemd160.cc.i

src/p2p/crypto/ripemd160.s: src/p2p/crypto/ripemd160.cc.s

.PHONY : src/p2p/crypto/ripemd160.s

# target to generate assembly for a file
src/p2p/crypto/ripemd160.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/ripemd160.cc.s
.PHONY : src/p2p/crypto/ripemd160.cc.s

src/p2p/crypto/sha1.o: src/p2p/crypto/sha1.cc.o

.PHONY : src/p2p/crypto/sha1.o

# target to build an object file
src/p2p/crypto/sha1.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/sha1.cc.o
.PHONY : src/p2p/crypto/sha1.cc.o

src/p2p/crypto/sha1.i: src/p2p/crypto/sha1.cc.i

.PHONY : src/p2p/crypto/sha1.i

# target to preprocess a source file
src/p2p/crypto/sha1.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/sha1.cc.i
.PHONY : src/p2p/crypto/sha1.cc.i

src/p2p/crypto/sha1.s: src/p2p/crypto/sha1.cc.s

.PHONY : src/p2p/crypto/sha1.s

# target to generate assembly for a file
src/p2p/crypto/sha1.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/sha1.cc.s
.PHONY : src/p2p/crypto/sha1.cc.s

src/p2p/crypto/sha256.o: src/p2p/crypto/sha256.cc.o

.PHONY : src/p2p/crypto/sha256.o

# target to build an object file
src/p2p/crypto/sha256.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/sha256.cc.o
.PHONY : src/p2p/crypto/sha256.cc.o

src/p2p/crypto/sha256.i: src/p2p/crypto/sha256.cc.i

.PHONY : src/p2p/crypto/sha256.i

# target to preprocess a source file
src/p2p/crypto/sha256.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/sha256.cc.i
.PHONY : src/p2p/crypto/sha256.cc.i

src/p2p/crypto/sha256.s: src/p2p/crypto/sha256.cc.s

.PHONY : src/p2p/crypto/sha256.s

# target to generate assembly for a file
src/p2p/crypto/sha256.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/sha256.cc.s
.PHONY : src/p2p/crypto/sha256.cc.s

src/p2p/crypto/sha256_avx2.o: src/p2p/crypto/sha256_avx2.cc.o

.PHONY : src/p2p/crypto/sha256_avx2.o

# target to build an object file
src/p2p/crypto/sha256_avx2.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/sha256_avx2.cc.o
.PHONY : src/p2p/crypto/sha256_avx2.cc.o

src/p2p/crypto/sha256_avx2.i: src/p2p/crypto/sha256_avx2.cc.i

.PHONY : src/p2p/crypto/sha256_avx2.i

# target to preprocess a source file
src/p2p/crypto/sha256_avx2.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/sha256_avx2.cc.i
.PHONY : src/p2p/crypto/sha256_avx2.cc.i

src/p2p/crypto/sha256_avx2.s: src/p2p/crypto/sha256_avx2.cc.s

.PHONY : src/p2p/crypto/sha256_avx2.s

# target to generate assembly for a file
src/p2p/crypto/sha256_avx2.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/sha256_avx2.cc.s
.PHONY : src/p2p/crypto/sha256_avx2.cc.s

src/p2p/crypto/sha256_shani.o: src/p2p/crypto/sha256_shani.cc.o

.PHONY : src/p2p/crypto/sha256_shani.o

# target to build an object file
src/p2p/crypto/sha256_shani.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/sha256_shani.cc.o
.PHONY : src/p2p/crypto/sha256_shani.cc.o

src/p2p/crypto/sha256_shani.i: src/p2p/crypto/sha256_shani.cc.i

.PHONY : src/p2p/crypto/sha256_shani.i

# target to preprocess a source file
src/p2p/crypto/sha256_shani.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/sha256_shani.cc.i
.PHONY : src/p2p/crypto/sha256_shani.cc.i

src/p2p/crypto/sha256_shani.s: src/p2p/crypto/sha256_shani.cc.s

.PHONY : src/p2p/crypto/sha256_shani.s

# target to generate assembly for a file
src/p2p/crypto/sha256_shani.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/sha256_shani.cc.s
.PHONY : src/p2p/crypto/sha256_shani.cc.s

src/p2p/crypto/sha256_sse4.o: src/p2p/crypto/sha256_sse4.cc.o

.PHONY : src/p2p/crypto/sha256_sse4.o

# target to build an object file
src/p2p/crypto/sha256_sse4.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/sha256_sse4.cc.o
.PHONY : src/p2p/crypto/sha256_sse4.cc.o

src/p2p/crypto/sha256_sse4.i: src/p2p/crypto/sha256_sse4.cc.i

.PHONY : src/p2p/crypto/sha256_sse4.i

# target to preprocess a source file
src/p2p/crypto/sha256_sse4.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/sha256_sse4.cc.i
.PHONY : src/p2p/crypto/sha256_sse4.cc.i

src/p2p/crypto/sha256_sse4.s: src/p2p/crypto/sha256_sse4.cc.s

.PHONY : src/p2p/crypto/sha256_sse4.s

# target to generate assembly for a file
src/p2p/crypto/sha256_sse4.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/sha256_sse4.cc.s
.PHONY : src/p2p/crypto/sha256_sse4.cc.s

src/p2p/crypto/sha256_sse41.o: src/p2p/crypto/sha256_sse41.cc.o

.PHONY : src/p2p/crypto/sha256_sse41.o

# target to build an object file
src/p2p/crypto/sha256_sse41.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/sha256_sse41.cc.o
.PHONY : src/p2p/crypto/sha256_sse41.cc.o

src/p2p/crypto/sha256_sse41.i: src/p2p/crypto/sha256_sse41.cc.i

.PHONY : src/p2p/crypto/sha256_sse41.i

# target to preprocess a source file
src/p2p/crypto/sha256_sse41.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/sha256_sse41.cc.i
.PHONY : src/p2p/crypto/sha256_sse41.cc.i

src/p2p/crypto/sha256_sse41.s: src/p2p/crypto/sha256_sse41.cc.s

.PHONY : src/p2p/crypto/sha256_sse41.s

# target to generate assembly for a file
src/p2p/crypto/sha256_sse41.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/sha256_sse41.cc.s
.PHONY : src/p2p/crypto/sha256_sse41.cc.s

src/p2p/crypto/sha512.o: src/p2p/crypto/sha512.cc.o

.PHONY : src/p2p/crypto/sha512.o

# target to build an object file
src/p2p/crypto/sha512.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/sha512.cc.o
.PHONY : src/p2p/crypto/sha512.cc.o

src/p2p/crypto/sha512.i: src/p2p/crypto/sha512.cc.i

.PHONY : src/p2p/crypto/sha512.i

# target to preprocess a source file
src/p2p/crypto/sha512.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/sha512.cc.i
.PHONY : src/p2p/crypto/sha512.cc.i

src/p2p/crypto/sha512.s: src/p2p/crypto/sha512.cc.s

.PHONY : src/p2p/crypto/sha512.s

# target to generate assembly for a file
src/p2p/crypto/sha512.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/crypto/sha512.cc.s
.PHONY : src/p2p/crypto/sha512.cc.s

src/p2p/fs.o: src/p2p/fs.cc.o

.PHONY : src/p2p/fs.o

# target to build an object file
src/p2p/fs.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/fs.cc.o
.PHONY : src/p2p/fs.cc.o

src/p2p/fs.i: src/p2p/fs.cc.i

.PHONY : src/p2p/fs.i

# target to preprocess a source file
src/p2p/fs.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/fs.cc.i
.PHONY : src/p2p/fs.cc.i

src/p2p/fs.s: src/p2p/fs.cc.s

.PHONY : src/p2p/fs.s

# target to generate assembly for a file
src/p2p/fs.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/fs.cc.s
.PHONY : src/p2p/fs.cc.s

src/p2p/hash.o: src/p2p/hash.cc.o

.PHONY : src/p2p/hash.o

# target to build an object file
src/p2p/hash.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/hash.cc.o
.PHONY : src/p2p/hash.cc.o

src/p2p/hash.i: src/p2p/hash.cc.i

.PHONY : src/p2p/hash.i

# target to preprocess a source file
src/p2p/hash.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/hash.cc.i
.PHONY : src/p2p/hash.cc.i

src/p2p/hash.s: src/p2p/hash.cc.s

.PHONY : src/p2p/hash.s

# target to generate assembly for a file
src/p2p/hash.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/hash.cc.s
.PHONY : src/p2p/hash.cc.s

src/p2p/init.o: src/p2p/init.cc.o

.PHONY : src/p2p/init.o

# target to build an object file
src/p2p/init.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/init.cc.o
.PHONY : src/p2p/init.cc.o

src/p2p/init.i: src/p2p/init.cc.i

.PHONY : src/p2p/init.i

# target to preprocess a source file
src/p2p/init.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/init.cc.i
.PHONY : src/p2p/init.cc.i

src/p2p/init.s: src/p2p/init.cc.s

.PHONY : src/p2p/init.s

# target to generate assembly for a file
src/p2p/init.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/init.cc.s
.PHONY : src/p2p/init.cc.s

src/p2p/logging.o: src/p2p/logging.cc.o

.PHONY : src/p2p/logging.o

# target to build an object file
src/p2p/logging.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/logging.cc.o
.PHONY : src/p2p/logging.cc.o

src/p2p/logging.i: src/p2p/logging.cc.i

.PHONY : src/p2p/logging.i

# target to preprocess a source file
src/p2p/logging.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/logging.cc.i
.PHONY : src/p2p/logging.cc.i

src/p2p/logging.s: src/p2p/logging.cc.s

.PHONY : src/p2p/logging.s

# target to generate assembly for a file
src/p2p/logging.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/logging.cc.s
.PHONY : src/p2p/logging.cc.s

src/p2p/net.o: src/p2p/net.cc.o

.PHONY : src/p2p/net.o

# target to build an object file
src/p2p/net.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/net.cc.o
.PHONY : src/p2p/net.cc.o

src/p2p/net.i: src/p2p/net.cc.i

.PHONY : src/p2p/net.i

# target to preprocess a source file
src/p2p/net.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/net.cc.i
.PHONY : src/p2p/net.cc.i

src/p2p/net.s: src/p2p/net.cc.s

.PHONY : src/p2p/net.s

# target to generate assembly for a file
src/p2p/net.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/net.cc.s
.PHONY : src/p2p/net.cc.s

src/p2p/net_processing.o: src/p2p/net_processing.cc.o

.PHONY : src/p2p/net_processing.o

# target to build an object file
src/p2p/net_processing.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/net_processing.cc.o
.PHONY : src/p2p/net_processing.cc.o

src/p2p/net_processing.i: src/p2p/net_processing.cc.i

.PHONY : src/p2p/net_processing.i

# target to preprocess a source file
src/p2p/net_processing.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/net_processing.cc.i
.PHONY : src/p2p/net_processing.cc.i

src/p2p/net_processing.s: src/p2p/net_processing.cc.s

.PHONY : src/p2p/net_processing.s

# target to generate assembly for a file
src/p2p/net_processing.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/net_processing.cc.s
.PHONY : src/p2p/net_processing.cc.s

src/p2p/netaddress.o: src/p2p/netaddress.cc.o

.PHONY : src/p2p/netaddress.o

# target to build an object file
src/p2p/netaddress.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/netaddress.cc.o
.PHONY : src/p2p/netaddress.cc.o

src/p2p/netaddress.i: src/p2p/netaddress.cc.i

.PHONY : src/p2p/netaddress.i

# target to preprocess a source file
src/p2p/netaddress.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/netaddress.cc.i
.PHONY : src/p2p/netaddress.cc.i

src/p2p/netaddress.s: src/p2p/netaddress.cc.s

.PHONY : src/p2p/netaddress.s

# target to generate assembly for a file
src/p2p/netaddress.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/netaddress.cc.s
.PHONY : src/p2p/netaddress.cc.s

src/p2p/netbase.o: src/p2p/netbase.cc.o

.PHONY : src/p2p/netbase.o

# target to build an object file
src/p2p/netbase.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/netbase.cc.o
.PHONY : src/p2p/netbase.cc.o

src/p2p/netbase.i: src/p2p/netbase.cc.i

.PHONY : src/p2p/netbase.i

# target to preprocess a source file
src/p2p/netbase.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/netbase.cc.i
.PHONY : src/p2p/netbase.cc.i

src/p2p/netbase.s: src/p2p/netbase.cc.s

.PHONY : src/p2p/netbase.s

# target to generate assembly for a file
src/p2p/netbase.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/netbase.cc.s
.PHONY : src/p2p/netbase.cc.s

src/p2p/protocol.o: src/p2p/protocol.cc.o

.PHONY : src/p2p/protocol.o

# target to build an object file
src/p2p/protocol.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/protocol.cc.o
.PHONY : src/p2p/protocol.cc.o

src/p2p/protocol.i: src/p2p/protocol.cc.i

.PHONY : src/p2p/protocol.i

# target to preprocess a source file
src/p2p/protocol.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/protocol.cc.i
.PHONY : src/p2p/protocol.cc.i

src/p2p/protocol.s: src/p2p/protocol.cc.s

.PHONY : src/p2p/protocol.s

# target to generate assembly for a file
src/p2p/protocol.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/protocol.cc.s
.PHONY : src/p2p/protocol.cc.s

src/p2p/random.o: src/p2p/random.cc.o

.PHONY : src/p2p/random.o

# target to build an object file
src/p2p/random.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/random.cc.o
.PHONY : src/p2p/random.cc.o

src/p2p/random.i: src/p2p/random.cc.i

.PHONY : src/p2p/random.i

# target to preprocess a source file
src/p2p/random.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/random.cc.i
.PHONY : src/p2p/random.cc.i

src/p2p/random.s: src/p2p/random.cc.s

.PHONY : src/p2p/random.s

# target to generate assembly for a file
src/p2p/random.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/random.cc.s
.PHONY : src/p2p/random.cc.s

src/p2p/scheduler.o: src/p2p/scheduler.cc.o

.PHONY : src/p2p/scheduler.o

# target to build an object file
src/p2p/scheduler.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/scheduler.cc.o
.PHONY : src/p2p/scheduler.cc.o

src/p2p/scheduler.i: src/p2p/scheduler.cc.i

.PHONY : src/p2p/scheduler.i

# target to preprocess a source file
src/p2p/scheduler.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/scheduler.cc.i
.PHONY : src/p2p/scheduler.cc.i

src/p2p/scheduler.s: src/p2p/scheduler.cc.s

.PHONY : src/p2p/scheduler.s

# target to generate assembly for a file
src/p2p/scheduler.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/scheduler.cc.s
.PHONY : src/p2p/scheduler.cc.s

src/p2p/shutdown.o: src/p2p/shutdown.cc.o

.PHONY : src/p2p/shutdown.o

# target to build an object file
src/p2p/shutdown.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/shutdown.cc.o
.PHONY : src/p2p/shutdown.cc.o

src/p2p/shutdown.i: src/p2p/shutdown.cc.i

.PHONY : src/p2p/shutdown.i

# target to preprocess a source file
src/p2p/shutdown.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/shutdown.cc.i
.PHONY : src/p2p/shutdown.cc.i

src/p2p/shutdown.s: src/p2p/shutdown.cc.s

.PHONY : src/p2p/shutdown.s

# target to generate assembly for a file
src/p2p/shutdown.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/shutdown.cc.s
.PHONY : src/p2p/shutdown.cc.s

src/p2p/support/cleanse.o: src/p2p/support/cleanse.cc.o

.PHONY : src/p2p/support/cleanse.o

# target to build an object file
src/p2p/support/cleanse.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/support/cleanse.cc.o
.PHONY : src/p2p/support/cleanse.cc.o

src/p2p/support/cleanse.i: src/p2p/support/cleanse.cc.i

.PHONY : src/p2p/support/cleanse.i

# target to preprocess a source file
src/p2p/support/cleanse.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/support/cleanse.cc.i
.PHONY : src/p2p/support/cleanse.cc.i

src/p2p/support/cleanse.s: src/p2p/support/cleanse.cc.s

.PHONY : src/p2p/support/cleanse.s

# target to generate assembly for a file
src/p2p/support/cleanse.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/support/cleanse.cc.s
.PHONY : src/p2p/support/cleanse.cc.s

src/p2p/support/lockedpool.o: src/p2p/support/lockedpool.cc.o

.PHONY : src/p2p/support/lockedpool.o

# target to build an object file
src/p2p/support/lockedpool.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/support/lockedpool.cc.o
.PHONY : src/p2p/support/lockedpool.cc.o

src/p2p/support/lockedpool.i: src/p2p/support/lockedpool.cc.i

.PHONY : src/p2p/support/lockedpool.i

# target to preprocess a source file
src/p2p/support/lockedpool.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/support/lockedpool.cc.i
.PHONY : src/p2p/support/lockedpool.cc.i

src/p2p/support/lockedpool.s: src/p2p/support/lockedpool.cc.s

.PHONY : src/p2p/support/lockedpool.s

# target to generate assembly for a file
src/p2p/support/lockedpool.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/support/lockedpool.cc.s
.PHONY : src/p2p/support/lockedpool.cc.s

src/p2p/sync.o: src/p2p/sync.cc.o

.PHONY : src/p2p/sync.o

# target to build an object file
src/p2p/sync.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/sync.cc.o
.PHONY : src/p2p/sync.cc.o

src/p2p/sync.i: src/p2p/sync.cc.i

.PHONY : src/p2p/sync.i

# target to preprocess a source file
src/p2p/sync.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/sync.cc.i
.PHONY : src/p2p/sync.cc.i

src/p2p/sync.s: src/p2p/sync.cc.s

.PHONY : src/p2p/sync.s

# target to generate assembly for a file
src/p2p/sync.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/sync.cc.s
.PHONY : src/p2p/sync.cc.s

src/p2p/threadinterrupt.o: src/p2p/threadinterrupt.cc.o

.PHONY : src/p2p/threadinterrupt.o

# target to build an object file
src/p2p/threadinterrupt.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/threadinterrupt.cc.o
.PHONY : src/p2p/threadinterrupt.cc.o

src/p2p/threadinterrupt.i: src/p2p/threadinterrupt.cc.i

.PHONY : src/p2p/threadinterrupt.i

# target to preprocess a source file
src/p2p/threadinterrupt.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/threadinterrupt.cc.i
.PHONY : src/p2p/threadinterrupt.cc.i

src/p2p/threadinterrupt.s: src/p2p/threadinterrupt.cc.s

.PHONY : src/p2p/threadinterrupt.s

# target to generate assembly for a file
src/p2p/threadinterrupt.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/threadinterrupt.cc.s
.PHONY : src/p2p/threadinterrupt.cc.s

src/p2p/timedata.o: src/p2p/timedata.cc.o

.PHONY : src/p2p/timedata.o

# target to build an object file
src/p2p/timedata.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/timedata.cc.o
.PHONY : src/p2p/timedata.cc.o

src/p2p/timedata.i: src/p2p/timedata.cc.i

.PHONY : src/p2p/timedata.i

# target to preprocess a source file
src/p2p/timedata.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/timedata.cc.i
.PHONY : src/p2p/timedata.cc.i

src/p2p/timedata.s: src/p2p/timedata.cc.s

.PHONY : src/p2p/timedata.s

# target to generate assembly for a file
src/p2p/timedata.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/timedata.cc.s
.PHONY : src/p2p/timedata.cc.s

src/p2p/uint256.o: src/p2p/uint256.cc.o

.PHONY : src/p2p/uint256.o

# target to build an object file
src/p2p/uint256.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/uint256.cc.o
.PHONY : src/p2p/uint256.cc.o

src/p2p/uint256.i: src/p2p/uint256.cc.i

.PHONY : src/p2p/uint256.i

# target to preprocess a source file
src/p2p/uint256.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/uint256.cc.i
.PHONY : src/p2p/uint256.cc.i

src/p2p/uint256.s: src/p2p/uint256.cc.s

.PHONY : src/p2p/uint256.s

# target to generate assembly for a file
src/p2p/uint256.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/uint256.cc.s
.PHONY : src/p2p/uint256.cc.s

src/p2p/util.o: src/p2p/util.cc.o

.PHONY : src/p2p/util.o

# target to build an object file
src/p2p/util.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/util.cc.o
.PHONY : src/p2p/util.cc.o

src/p2p/util.i: src/p2p/util.cc.i

.PHONY : src/p2p/util.i

# target to preprocess a source file
src/p2p/util.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/util.cc.i
.PHONY : src/p2p/util.cc.i

src/p2p/util.s: src/p2p/util.cc.s

.PHONY : src/p2p/util.s

# target to generate assembly for a file
src/p2p/util.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/util.cc.s
.PHONY : src/p2p/util.cc.s

src/p2p/utilstrencodings.o: src/p2p/utilstrencodings.cc.o

.PHONY : src/p2p/utilstrencodings.o

# target to build an object file
src/p2p/utilstrencodings.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/utilstrencodings.cc.o
.PHONY : src/p2p/utilstrencodings.cc.o

src/p2p/utilstrencodings.i: src/p2p/utilstrencodings.cc.i

.PHONY : src/p2p/utilstrencodings.i

# target to preprocess a source file
src/p2p/utilstrencodings.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/utilstrencodings.cc.i
.PHONY : src/p2p/utilstrencodings.cc.i

src/p2p/utilstrencodings.s: src/p2p/utilstrencodings.cc.s

.PHONY : src/p2p/utilstrencodings.s

# target to generate assembly for a file
src/p2p/utilstrencodings.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/utilstrencodings.cc.s
.PHONY : src/p2p/utilstrencodings.cc.s

src/p2p/utiltime.o: src/p2p/utiltime.cc.o

.PHONY : src/p2p/utiltime.o

# target to build an object file
src/p2p/utiltime.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/utiltime.cc.o
.PHONY : src/p2p/utiltime.cc.o

src/p2p/utiltime.i: src/p2p/utiltime.cc.i

.PHONY : src/p2p/utiltime.i

# target to preprocess a source file
src/p2p/utiltime.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/utiltime.cc.i
.PHONY : src/p2p/utiltime.cc.i

src/p2p/utiltime.s: src/p2p/utiltime.cc.s

.PHONY : src/p2p/utiltime.s

# target to generate assembly for a file
src/p2p/utiltime.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/p2p/utiltime.cc.s
.PHONY : src/p2p/utiltime.cc.s

src/server/ambrd.o: src/server/ambrd.cc.o

.PHONY : src/server/ambrd.o

# target to build an object file
src/server/ambrd.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/server/ambrd.cc.o
.PHONY : src/server/ambrd.cc.o

src/server/ambrd.i: src/server/ambrd.cc.i

.PHONY : src/server/ambrd.i

# target to preprocess a source file
src/server/ambrd.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/server/ambrd.cc.i
.PHONY : src/server/ambrd.cc.i

src/server/ambrd.s: src/server/ambrd.cc.s

.PHONY : src/server/ambrd.s

# target to generate assembly for a file
src/server/ambrd.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/server/ambrd.cc.s
.PHONY : src/server/ambrd.cc.s

src/server/server_interface.o: src/server/server_interface.cc.o

.PHONY : src/server/server_interface.o

# target to build an object file
src/server/server_interface.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/server/server_interface.cc.o
.PHONY : src/server/server_interface.cc.o

src/server/server_interface.i: src/server/server_interface.cc.i

.PHONY : src/server/server_interface.i

# target to preprocess a source file
src/server/server_interface.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/server/server_interface.cc.i
.PHONY : src/server/server_interface.cc.i

src/server/server_interface.s: src/server/server_interface.cc.s

.PHONY : src/server/server_interface.s

# target to generate assembly for a file
src/server/server_interface.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/server/server_interface.cc.s
.PHONY : src/server/server_interface.cc.s

src/store/store_manager.o: src/store/store_manager.cc.o

.PHONY : src/store/store_manager.o

# target to build an object file
src/store/store_manager.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/store/store_manager.cc.o
.PHONY : src/store/store_manager.cc.o

src/store/store_manager.i: src/store/store_manager.cc.i

.PHONY : src/store/store_manager.i

# target to preprocess a source file
src/store/store_manager.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/store/store_manager.cc.i
.PHONY : src/store/store_manager.cc.i

src/store/store_manager.s: src/store/store_manager.cc.s

.PHONY : src/store/store_manager.s

# target to generate assembly for a file
src/store/store_manager.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/store/store_manager.cc.s
.PHONY : src/store/store_manager.cc.s

src/store/unit_store.o: src/store/unit_store.cc.o

.PHONY : src/store/unit_store.o

# target to build an object file
src/store/unit_store.cc.o:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/store/unit_store.cc.o
.PHONY : src/store/unit_store.cc.o

src/store/unit_store.i: src/store/unit_store.cc.i

.PHONY : src/store/unit_store.i

# target to preprocess a source file
src/store/unit_store.cc.i:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/store/unit_store.cc.i
.PHONY : src/store/unit_store.cc.i

src/store/unit_store.s: src/store/unit_store.cc.s

.PHONY : src/store/unit_store.s

# target to generate assembly for a file
src/store/unit_store.cc.s:
	$(MAKE) -f CMakeFiles/Ambr.dir/build.make CMakeFiles/Ambr.dir/src/store/unit_store.cc.s
.PHONY : src/store/unit_store.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Ambr"
	@echo "... arch/linux/platform.o"
	@echo "... arch/linux/platform.i"
	@echo "... arch/linux/platform.s"
	@echo "... libs/ed25519-donna/ed25519.o"
	@echo "... libs/ed25519-donna/ed25519.i"
	@echo "... libs/ed25519-donna/ed25519.s"
	@echo "... src/core/key.o"
	@echo "... src/core/key.i"
	@echo "... src/core/key.s"
	@echo "... src/core/node.o"
	@echo "... src/core/node.i"
	@echo "... src/core/node.s"
	@echo "... src/core/unit.o"
	@echo "... src/core/unit.i"
	@echo "... src/core/unit.s"
	@echo "... src/crypto/blake2/blake2b.o"
	@echo "... src/crypto/blake2/blake2b.i"
	@echo "... src/crypto/blake2/blake2b.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/p2p/addrdb.o"
	@echo "... src/p2p/addrdb.i"
	@echo "... src/p2p/addrdb.s"
	@echo "... src/p2p/addrman.o"
	@echo "... src/p2p/addrman.i"
	@echo "... src/p2p/addrman.s"
	@echo "... src/p2p/arith_uint256.o"
	@echo "... src/p2p/arith_uint256.i"
	@echo "... src/p2p/arith_uint256.s"
	@echo "... src/p2p/chainparams.o"
	@echo "... src/p2p/chainparams.i"
	@echo "... src/p2p/chainparams.s"
	@echo "... src/p2p/chainparamsbase.o"
	@echo "... src/p2p/chainparamsbase.i"
	@echo "... src/p2p/chainparamsbase.s"
	@echo "... src/p2p/compat/glibc_compat.o"
	@echo "... src/p2p/compat/glibc_compat.i"
	@echo "... src/p2p/compat/glibc_compat.s"
	@echo "... src/p2p/compat/glibc_sanity.o"
	@echo "... src/p2p/compat/glibc_sanity.i"
	@echo "... src/p2p/compat/glibc_sanity.s"
	@echo "... src/p2p/compat/glibcxx_sanity.o"
	@echo "... src/p2p/compat/glibcxx_sanity.i"
	@echo "... src/p2p/compat/glibcxx_sanity.s"
	@echo "... src/p2p/compat/strnlen.o"
	@echo "... src/p2p/compat/strnlen.i"
	@echo "... src/p2p/compat/strnlen.s"
	@echo "... src/p2p/crypto/aes.o"
	@echo "... src/p2p/crypto/aes.i"
	@echo "... src/p2p/crypto/aes.s"
	@echo "... src/p2p/crypto/chacha20.o"
	@echo "... src/p2p/crypto/chacha20.i"
	@echo "... src/p2p/crypto/chacha20.s"
	@echo "... src/p2p/crypto/hmac_sha256.o"
	@echo "... src/p2p/crypto/hmac_sha256.i"
	@echo "... src/p2p/crypto/hmac_sha256.s"
	@echo "... src/p2p/crypto/hmac_sha512.o"
	@echo "... src/p2p/crypto/hmac_sha512.i"
	@echo "... src/p2p/crypto/hmac_sha512.s"
	@echo "... src/p2p/crypto/ripemd160.o"
	@echo "... src/p2p/crypto/ripemd160.i"
	@echo "... src/p2p/crypto/ripemd160.s"
	@echo "... src/p2p/crypto/sha1.o"
	@echo "... src/p2p/crypto/sha1.i"
	@echo "... src/p2p/crypto/sha1.s"
	@echo "... src/p2p/crypto/sha256.o"
	@echo "... src/p2p/crypto/sha256.i"
	@echo "... src/p2p/crypto/sha256.s"
	@echo "... src/p2p/crypto/sha256_avx2.o"
	@echo "... src/p2p/crypto/sha256_avx2.i"
	@echo "... src/p2p/crypto/sha256_avx2.s"
	@echo "... src/p2p/crypto/sha256_shani.o"
	@echo "... src/p2p/crypto/sha256_shani.i"
	@echo "... src/p2p/crypto/sha256_shani.s"
	@echo "... src/p2p/crypto/sha256_sse4.o"
	@echo "... src/p2p/crypto/sha256_sse4.i"
	@echo "... src/p2p/crypto/sha256_sse4.s"
	@echo "... src/p2p/crypto/sha256_sse41.o"
	@echo "... src/p2p/crypto/sha256_sse41.i"
	@echo "... src/p2p/crypto/sha256_sse41.s"
	@echo "... src/p2p/crypto/sha512.o"
	@echo "... src/p2p/crypto/sha512.i"
	@echo "... src/p2p/crypto/sha512.s"
	@echo "... src/p2p/fs.o"
	@echo "... src/p2p/fs.i"
	@echo "... src/p2p/fs.s"
	@echo "... src/p2p/hash.o"
	@echo "... src/p2p/hash.i"
	@echo "... src/p2p/hash.s"
	@echo "... src/p2p/init.o"
	@echo "... src/p2p/init.i"
	@echo "... src/p2p/init.s"
	@echo "... src/p2p/logging.o"
	@echo "... src/p2p/logging.i"
	@echo "... src/p2p/logging.s"
	@echo "... src/p2p/net.o"
	@echo "... src/p2p/net.i"
	@echo "... src/p2p/net.s"
	@echo "... src/p2p/net_processing.o"
	@echo "... src/p2p/net_processing.i"
	@echo "... src/p2p/net_processing.s"
	@echo "... src/p2p/netaddress.o"
	@echo "... src/p2p/netaddress.i"
	@echo "... src/p2p/netaddress.s"
	@echo "... src/p2p/netbase.o"
	@echo "... src/p2p/netbase.i"
	@echo "... src/p2p/netbase.s"
	@echo "... src/p2p/protocol.o"
	@echo "... src/p2p/protocol.i"
	@echo "... src/p2p/protocol.s"
	@echo "... src/p2p/random.o"
	@echo "... src/p2p/random.i"
	@echo "... src/p2p/random.s"
	@echo "... src/p2p/scheduler.o"
	@echo "... src/p2p/scheduler.i"
	@echo "... src/p2p/scheduler.s"
	@echo "... src/p2p/shutdown.o"
	@echo "... src/p2p/shutdown.i"
	@echo "... src/p2p/shutdown.s"
	@echo "... src/p2p/support/cleanse.o"
	@echo "... src/p2p/support/cleanse.i"
	@echo "... src/p2p/support/cleanse.s"
	@echo "... src/p2p/support/lockedpool.o"
	@echo "... src/p2p/support/lockedpool.i"
	@echo "... src/p2p/support/lockedpool.s"
	@echo "... src/p2p/sync.o"
	@echo "... src/p2p/sync.i"
	@echo "... src/p2p/sync.s"
	@echo "... src/p2p/threadinterrupt.o"
	@echo "... src/p2p/threadinterrupt.i"
	@echo "... src/p2p/threadinterrupt.s"
	@echo "... src/p2p/timedata.o"
	@echo "... src/p2p/timedata.i"
	@echo "... src/p2p/timedata.s"
	@echo "... src/p2p/uint256.o"
	@echo "... src/p2p/uint256.i"
	@echo "... src/p2p/uint256.s"
	@echo "... src/p2p/util.o"
	@echo "... src/p2p/util.i"
	@echo "... src/p2p/util.s"
	@echo "... src/p2p/utilstrencodings.o"
	@echo "... src/p2p/utilstrencodings.i"
	@echo "... src/p2p/utilstrencodings.s"
	@echo "... src/p2p/utiltime.o"
	@echo "... src/p2p/utiltime.i"
	@echo "... src/p2p/utiltime.s"
	@echo "... src/server/ambrd.o"
	@echo "... src/server/ambrd.i"
	@echo "... src/server/ambrd.s"
	@echo "... src/server/server_interface.o"
	@echo "... src/server/server_interface.i"
	@echo "... src/server/server_interface.s"
	@echo "... src/store/store_manager.o"
	@echo "... src/store/store_manager.i"
	@echo "... src/store/store_manager.s"
	@echo "... src/store/unit_store.o"
	@echo "... src/store/unit_store.i"
	@echo "... src/store/unit_store.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

